# Generated by Django 4.2 on 2024-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_contactform_contact_form_uuid_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=55, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
