# Generated by Django 4.2.13 on 2024-05-23 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_flan_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("image_url", models.URLField()),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_private", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Flan",
        ),
    ]
