# Generated by Django 4.2.13 on 2024-05-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_producto_delete_flan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coctel",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.producto",
                    ),
                ),
                ("tipo_coctel", models.CharField(max_length=100)),
            ],
            bases=("web.producto",),
        ),
        migrations.CreateModel(
            name="Dulce",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.producto",
                    ),
                ),
                ("tipo_dulce", models.CharField(max_length=100)),
            ],
            bases=("web.producto",),
        ),
        migrations.CreateModel(
            name="Pasta",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.producto",
                    ),
                ),
                ("tipo_pasta", models.CharField(max_length=100)),
            ],
            bases=("web.producto",),
        ),
        migrations.CreateModel(
            name="Salsa",
            fields=[
                (
                    "producto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="web.producto",
                    ),
                ),
                ("tipo_salsa", models.CharField(max_length=100)),
            ],
            bases=("web.producto",),
        ),
    ]
