# Generated by Django 4.2.13 on 2024-05-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_coctel_dulce_pasta_salsa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
