# Generated by Django 4.2.13 on 2024-05-25 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_producto_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="image_url",
            new_name="image",
        ),
    ]
